# Generated by Django 4.2.19 on 2025-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/cv/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/id/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/photos/'),
        ),
    ]
