# Generated by Django 4.2.19 on 2025-02-13 00:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_timesheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-start_time'], 'verbose_name': 'Timesheet', 'verbose_name_plural': 'Timesheets'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, help_text="Employee's CV (optional)", null=True, upload_to='uploads/documents/cv/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(help_text="Employee's date of birth"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('MARKETING', 'Marketing'), ('SALES', 'Sales'), ('OPERATIONS', 'Operations'), ('LEGAL', 'Legal')], help_text="Employee's department", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text="Employee's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(help_text="Employee's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_document',
            field=models.FileField(blank=True, help_text="Employee's ID document (optional)", null=True, upload_to='uploads/documents/id/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('MANAGER', 'Manager'), ('ANALYST', 'Analyst'), ('DESIGNER', 'Designer'), ('COORDINATOR', 'Coordinator'), ('SPECIALIST', 'Specialist'), ('DIRECTOR', 'Director'), ('CONSULTANT', 'Consultant')], help_text="Employee's job title", max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text="Employee's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text="Employee's phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text="Employee's photo (optional)", null=True, upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text="Employee's annual salary", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('15000.00'))]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(help_text="Employee's start date", validators=[employees.utils.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(help_text='Employee this timesheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_time',
            field=models.DateTimeField(help_text='End time of work period'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of work period'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary of work done'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['-start_time'], name='employees_t_start_t_af192d_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee'], name='employees_t_employe_2f2be0_idx'),
        ),
    ]
